- name: service-name
  address: 127.0.0.1
  id: service-id
  port: 80
  tags:
    - tag-1
    - tag-2
  meta:
    key: value
- name: service-name
  address: 127.0.0.1
  id: service-id-2
  port: 80
  tags:
    - tag-1
    - tag-2
  meta:
    key: value
  node:
    node: node-1
    address: 127.0.0.1

