version: '3'

services:
    pinchy-1:
      image: insidieux/pinchy:v1.1.0
      volumes:
        - ./configs/source/file:/etc/pinchy
      command:
        - 'file'
        - 'consul-agent'
        - '--source.path'
        - '/etc/pinchy/consul-agent.yml'
        - '--registry.address'
        - 'http://consul:8500'
        - 'once'
    pinchy-2:
      image: insidieux/pinchy:v1.1.0
      volumes:
        - ./configs/source/file:/etc/pinchy
      command:
        - 'file'
        - 'consul-catalog'
        - '--source.path'
        - '/etc/pinchy/consul-catalog.yml'
        - '--registry.address'
        - 'http://consul:8500'
        - 'once'

