version: '3'

services:
    pinchy:
      image: insidieux/pinchy:v1.0.0
      volumes:
        - ./configs/source/file:/etc/pinchy
      command:
        - 'file'
        - 'consul'
        - '--source.path'
        - '/etc/pinchy/example.yml'
        - '--registry.address'
        - 'http://consul:8500'
        - 'once'
